<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app-on.ico</ApplicationIcon>
    <AssemblyName>keepawake</AssemblyName>
    <RootNamespace>Keepawake</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Assets\app-on.ico" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets\app-off.ico" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Assets\generate-icon.ps1" />
    <None Include="Fonts\martian_mono_regular.ttf" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
